language: node_js
node_js:
  - "7"

# Yarn wants us to use apt-get but it's easier to use npm for traivs ...
before_script: ""
script: ./ci.sh

after_script:
  - 'bash <(curl -s https://codecov.io/bash) -f ./web/coverage/coverage-final.json'
